# Generated by Django 4.1.7 on 2023-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FilePathField(path='C:\\Django\\laboration_2\\webbramverk-laboration-2-sina3131\\Version-3\\static\\img')),
            ],
        ),
    ]
