# Generated by Django 4.1.7 on 2023-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
