# Generated by Django 4.1.7 on 2023-03-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_alter_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contanct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
