# Generated by Django 4.1.7 on 2023-03-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0005_contanct_country_contanct_email_contanct_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
