# Generated by Django 4.1.7 on 2023-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0006_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contanct',
            name='country',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='contanct',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contanct',
            name='mobile',
            field=models.IntegerField(default=' '),
        ),
        migrations.AlterField(
            model_name='contanct',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
